version: "3.8"
services:
  tour-service:
    build: .
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://db:27017/tourdb
    depends_on:
      - db

  db:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongodb_tour_data:/data/db

volumes:
  mongodb_tour_data:
