version: '3.8'
services:
  tour-package-service:
    build: .
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://tour-package-mongo:27017/tourPackageDB
    depends_on:
      - tour-package-mongo

  tour-package-mongo:
    image: mongo:5
    ports:
      - "27018:27017"
    volumes:
      - tour-package-data:/data/db

volumes:
  tour-package-data:
