services:
  user-service:
    build: .
    ports:
      - "3001:3001"
    environment:
      - DB_NAME=userdb
      - DB_USER=postgres
      - DB_PASSWORD=userpassword
      - DB_HOST=db
      - DB_PORT=5432
      - JWT_SECRET=your_jwt_secret
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=userpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
