version: "3.8"
services:
  payment-service:
    build: .
    ports:
      - "3004:3004"
    environment:
      - MONGO_URI=mongodb://db:27017/paymentdb
    depends_on:
      - db

  db:
    image: mongo:5
    ports:
      - "27018:27017"
    volumes:
      - mongodb_payment_data:/data/db

volumes:
  mongodb_payment_data:
