version: "3.8"
services:
  payment-service:
    build: .
    ports:
      - "3004:3004"
    environment:
      - MONGO_URI=mongodb://payment-mongo:27017/payment
    depends_on:
      - payment-mongo

  payment-mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - payment-mongo-data:/data/db

volumes:
  payment-mongo-data:
