version: "3.8"
services:
  booking-service:
    build: .
    ports:
      - "3003:3003"
    environment:
      - DB_NAME=bookingdb
      - DB_USER=postgres
      - DB_PASSWORD=bookingpassword
      - DB_HOST=db
      - DB_PORT=5433
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=bookingdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bookingpassword
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_booking_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_booking_data:
