version: '3.8'

services:
  app:
    build: .
    ports:
      - "3003:3003"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/booking


  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: booking
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"