version: '3.8'
services:
  inventory-service:
    build: .
    ports:
      - "3005:3005"
    environment:
      - MONGO_URI=mongodb://inventory-mongo:27017/inventoryDB
      - NODE_ENV=development
      - PORT=3005
    depends_on:
      - inventory-mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: node src/index.js
    restart: unless-stopped
    networks:
      - inventory-network

  inventory-mongo:
    image: mongo:5
    ports:
      - "27018:27017"
    volumes:
      - inventory-data:/data/db
    restart: unless-stopped
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge

volumes:
  inventory-data:
