version: "3.8"
services:
  inventory-service:
    build: .
    ports:
      - "3005:3005"
    environment:
      - MONGO_URI=mongodb://db:27017/inventorydb
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mongo:5
    ports:
      - "27019:27017"
    volumes:
      - mongodb_inventory_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  mongodb_inventory_data:
